#!/bin/bash

if [ -z $JAVA_HOME ]; then
	JAVAC='javac'
else
	JAVAC=$JAVA_HOME/bin/javac
fi

echo compiling A-D...
$JAVAC -cp .:llpl.jar workshop/A_intarray/*.java workshop/B_anyintarray/*.java workshop/C_genericarray/*.java workshop/D_list/*.java workshop/util/*.java 
echo compiling E...
$JAVAC -cp .:workshop/E_recordlog/llpl.jar workshop/E_recordlog/*.java 

